### ISSUE TITLE
error

### ISSUE THREAD

**Issue by gitmikoy** [cmusphinx/g2p-seq2seq#119]
i ran this command:
`g2p-seq2seq --interactive --model_dir ./g2p-seq2seq-cmudict`

then I get this error:
```
/usr/lib64/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/usr/bin/g2p-seq2seq", line 9, in <module>
    load_entry_point('g2p-seq2seq==6.1.3a0', 'console_scripts', 'g2p-seq2seq')()
  File "/usr/lib/python2.7/site-packages/g2p_seq2seq-6.1.3a0-py2.7.egg/g2p_seq2seq/app.py", line 107, in main
    params.hparams = g2p_trainer_utils.load_params(FLAGS.model_dir)
  File "/usr/lib/python2.7/site-packages/g2p_seq2seq-6.1.3a0-py2.7.egg/g2p_seq2seq/g2p_trainer_utils.py", line 210, in load_params
    model_params = json.load(open(params_file_path))
  File "/usr/lib64/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by mischmerz** [comment]
Same here. Tried tf from 1.0 to current. It's either missing "eager" or comes up with "No JSON object could be decoded" . Test suite fails also. 

m.

**Comment by mischmerz** [comment]
I get the tests  to run with tensorflow / tensor2tensor 1.5.x . However .. something seems to be wrong with model.params in g2p-seq2seq-cmudict . g2p_trainer_utils.py tries to load and de-json it, but fails. Tried to re-format it into something more json {  num_layers:2, size:512 } with or without (double-) quotes results in even more cryptic errors. No joy. That's particular bad because the CMU lmtool website has problems too.

**Comment by nurtas-m** [comment]
Hello
The model uploaded [here](https://sourceforge.net/projects/cmusphinx/files/G2P%20Models/g2p-seq2seq-cmudict.tar.gz/download) is invalid now.
Can you, please, train new model by yourself, and then use it in interactive mode?

**Comment by gitmikoy** [comment]
I tried to train a model using the cmudict.dict file
`g2p-seq2seq --train cmudict.dict --model_dir hahaha/`

now I get this error:

I'm running on VM Centos 7
tensorflow-1.8.0:
tensor2tensor-1.5.7

**Comment by nurtas-m** [comment]
@gitmikoy,

> I was able to progress.. maybe its currently training now. I ran the command like this.
g2p-seq2seq --train cmudict-master/cmudict.dict --model_dir test/

Its weird because I have to put the dict file into a folder for it to work somehow.

Are you sure, that in first time when you run the program there was cmudict.dict file in your current directory? When you launch the program you have to specify the path to the dictionary, but not just a name of the dictionary:
`g2p-seq2seq --train path/to/the/dictionary --model_dir hahaha`

> Does it take long time to train a model?
Depends on how accurate model do you want to receive. In my experiences you can get the best model after ~70.000 steps (on 1 GPU it takes about 2 hours). The training will stop after 200.000 steps. You may, manually stop the training process at any moment.

**Comment by nurtas-m** [comment]
@gitmikoy,
Is the problem solved now?

**Comment by gitmikoy** [comment]
@nurtas
Sorry I was not able to reply right away.. I was sure the file cmudict.dict was there when in in the terminal because use the tab key to find it.. but when the cmudict is inside the folder things seem to work like the command I used above.

I'm currently training the model  on cpu only (takes very long time) and targeting to 70,000 steps like you suggested.
Thank you nurtas for helping me :)

**Comment by nshmyrev** [comment]
Duplicate of issue #115
