### ISSUE TITLE
What is the input to the encoder network ?

### ISSUE THREAD

**Issue by llROOTll** [cmusphinx/g2p-seq2seq#139]
Hi,
As you mentioned in the readme that current version uses the attention mechanism from the transformer model. As in the transformer paper they use embeddings of the words as input. Does the current version of g2p-seq2seq also uses the input as vector embeddings of the tokens (in this case characters) or the encoder sees the tokens as they are ?

**Comment by llROOTll** [comment]
Sorry, just found your comment on this [issue](https://github.com/cmusphinx/g2p-seq2seq/issues/51).

**Comment by nurtas-m** [comment]
Hello, @llrootll 
Yes, as transformer uses embeddings of the words we also uses embeddings in g2p-seq2seq. But, in our case, we uses embeddings of the graphemes and phonemes instead of the embeddings of the words.
Because of transformer model trains embedding layer itself you don't need to worry about it.
