### ISSUE TITLE
Model not found after G2P training

### ISSUE THREAD

**Issue by ellurunaresh** [cmusphinx/g2p-seq2seq#88]
Hi all,
 I have installed g2p-seq2seq package successfully. I ran **test** directory and **CMU dictionary model** it worked fine. If I ran with 50 word training dictionary I am not able to save my model.  It shows **model not found**

Tensorflow Version: 1.0.0
Python: 3.5.4
conda 4.3.21

C:\Users\naresh.kumar\AppData\Local\Continuum\Anaconda3\envs\tensorflow\Scripts\g2p-seq2seq.exe --train seq-seq_IE\train_tmp.txt --size 512 --model seq-seq_IE\train_tmp_model

Created model with fresh parameters.
global step 200 learning rate 0.5000 step-time 1.61 perplexity 4.67
eval: perplexity 1.55
global step 400 learning rate 0.5000 step-time 1.42 perplexity 1.48
eval: perplexity 2.04
No improvement over last 1 times. Training will stop after -1iterations if no improvement was seen.
**Training done.**
Traceback (most recent call last):
File "C:\Users\naresh.kumar\AppData\Local\Continuum\Anaconda3\envs\tensorflow\Scripts\g2p-seq2seq-script.py", line 11, in 
load_entry_point('g2p-seq2seq==5.0.0a0', 'console_scripts', 'g2p-seq2seq')()
File "C:\Users\naresh.kumar\AppData\Local\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\g2p_seq2seq-5.0.0a0-py3.5.egg\g2p_seq2seq\app.py", line 80, in main
File "C:\Users\naresh.kumar\AppData\Local\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\g2p_seq2seq-5.0.0a0-py3.5.egg\g2p_seq2seq\g2p.py", line 278, in train
File "C:\Users\naresh.kumar\AppData\Local\Continuum\Anaconda3\envs\tensorflow\lib\site-packages\g2p_seq2seq-5.0.0a0-py3.5.egg\g2p_seq2seq\g2p.py", line 72, in load_decode_model
RuntimeError: Model not found in seq-seq_IE\test_exp

Please help me out how to solve this issue

**Comment by ellurunaresh** [comment]
Can anybody please explain me why I got this error.

**Comment by nurtas-m** [comment]
Hello, ellurunaresh!
It seems that the directory where you saved the model and the directory from which the program try to load the model are different.

When you run this script:
C:\Users\naresh.kumar\AppData\Local\Continuum\Anaconda3\envs\tensorflow\Scripts\g2p-seq2seq.exe --train seq-seq_IE\train_tmp.txt --size 512 --model seq-seq_IE\train_tmp_model

The program will try to load the model to continue training if there are exist "model.data-00000-of-00001" and "checkpoint" files in seq-seq_IE\train_tmp_model directory. Otherwise, the program will create new model in seq-seq_IE\train_tmp_model directory. After, training completed, evaluation mode turn on (with the same model directory). I suppose, that you had manually changed the directory to the model. Because from Logs that you provided, I see that the evaluation mode try to load model from other directory: seq-seq_IE\test_exp

**Comment by nurtas-m** [comment]
Closed, because it is irrelevant anymore.
