### ISSUE TITLE
Stopping on Unicode Encode Error during Encoding

### ISSUE THREAD

**Issue by feddyfedfed** [cmusphinx/g2p-seq2seq#99]
Is it possible for encode mode to not stop when the vocabulary list includes unicode characters not on the range of the model?  I wanna be able to get a dictionary where those entries that are not handled by the model can simply be manually corrected.

**Comment by nurtas-m** [comment]
Encoding on which stage do you interested in (on training stage or on decoding stage)? Do you mean that after training the model with some dataset (which initially not included some Unicode characters), you want to decode certain words with characters not from initial vocabulary? If so, it's not possible. Because when you use already trained model, on decoding stage you can't modify the architecture of the Neural Network.

**Comment by feddyfedfed** [comment]
Yes, the latter case.  I know it's not possible, but I would like the error handler to at least simply skip these words instead of stopping the batch process altogether.  I know I can simply write a workaround script for this but a built-in mechanism for handling such cases would be nice.
